repos:
-   repo: https://github.com/datarootsio/databooks
    rev: 1.0.5
    hooks:
    -   id: databooks-meta
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=300']
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-yaml
        exclude: .conda/meta.yaml
    -   id: requirements-txt-fixer
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.8.3
#     hooks:
#     -   id: flake8
#         additional_dependencies: [flake8-print, "importlib-metadata<5.0.0"]
#         args: [--config=setup.cfg]
#         exclude: ^examples/
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3
        additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: isort
        entry: python -m isort
        args: [--settings-path, ./pyproject.toml]
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
